apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cube-backend.fullname" . }}-config
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "cube-backend.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.env.databaseUrl | quote }}

