apiVersion: v2
name: cube-backend
description: A Helm chart for Kubernetes
type: application
version: 0.3.4
# appVersion est mis à jour automatiquement par Flux ImageUpdateAutomation
# Cela déclenche le HelmRelease (reconcileStrategy: ChartVersion)
appVersion: "main-6829293-1767790153" # {"$imagepolicy": "flux-system:cube-backend:tag"}
dependencies:
  - name: postgresql
    version: "15.5.38"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
